### PR TITLE
UT-Earthworks-12d-0

### PR DESCRIPTION
**Pull request by LeeGregory12d**
## Unit test

IfcSolidStratum of two tins.

## Covered topics

*tick one/many*

- [x] project setup
- [ ] georeferencing
- [ ] alignment semantics
- [ ] alignment geometry
- [ ] linear placement
- [ ] project breakdown structure / spatial structure
- [ ] terrain
- [x] triangulated irregular network
- [ ] open cross profile
- [ ] sectioned surface & solid
- [ ] pavement & course
- [ ] surface feature
- [ ] earthworks
- [ ] geotechnics
- [ ] longitudinal products (barriers, guardrail, ...)
- [ ] interchange
- [ ] structural
- [ ] drainage
- [ ] signage
- [ ] road furniture
- [ ] rail furniture
- [ ] ports & waterways furniture
- [ ] bridge furniture

### CODE REVIEW

**Comment by pjanck** [comment]
Following the changes to the schema, (we are now at `RC3`), we ask you to update your IFC files accordingly. The schema can be found [here](https://github.com/bSI-InfraRoom/IFC-Specification/blob/main/IFC4x3_RC3.exp). The checking procedure for IFC files has been updated - please merge in the current state of the `main` branch.

**Review by AlexBrad1eyCT — COMMENTED** [review]
The file is technically correct, but slightly confused on the practical structure,

you have 2 `IfcSolidStratum`s I assume representing 2 layers within the ground correct?
the percular part for me is that they each have their own parent facility? what is the reason for this?
Also `IfcSolidStratum` is defined to represent the survey geological context that is usually natural in source so i would usually associate IfcGeotechnicalElement subtypes to the site, unless client requirements specify soemthing else.

possible improvements:

- [ ]  (Optional) aggregate the `IfcSolidStratum`s under an `IfcGeoModel` to represent the entire 3d terrain profile.
- [ ] (Recommended) contain the `IfcSolidStratum` or `IfcGeoModel` within the site not unique facilities.

If there is reasoning behind the current structure please let me know!

**Comment by LeeGregory12d** [comment]
Alex,
I must admit I didn't think of the two tins represented two layer within the ground.
Being more into Civil Design I immediate thing of a ground surface and a design surface.

But yes the idea is general and what they actually mean would depend on the application.

**Comment by AlexBrad1eyCT** [comment]
Ah, That makes sense Lee, i understand now! in that case i would suggest making the ground surface contained in the site as above, and keep the design surface attached to a facility because its's built...
I would also suggest to name them Ground Surface & Design Surface in the readme and the file as this makes it alot easier to understand the intent of the file!

you have also highlighted a new use case for Stratum, to represent a design surface! did not think of that when creating the geotechnical parts.

**Comment by LeeGregory12d** [comment]
Alex,
It was pointed out in an earlier post in GitHub that I should be using IfcSolidStratum as IfcGeographicElement.PredefinedType was deprecated in IFC 4x3 RC1.

I have never thought of a Ground tin or Design tin or a Subbase tin as a being a "Solid Stratum" but it is as good as anything as long as that is the definition that everyone uses.
A tin being a  IfcGeographicElement was just a definition.

**Comment by AlexBrad1eyCT** [comment]
the way I divide it up is:

- Natural surveyed ground for example a new build site will always be solidstratums as either top surfaces or 3d shapes.
- something 'built' out of natural earthen or general material is a designed EarthworksFill
- something 'built' out of a controlled and graded aggregate thats usually compacted (graded sand, gravel, subbase) plus bonded materials asphelt and cement bound material is an IfcCourse.
- when we void an area by digging its an EarthworksCut
- additionally if we want to represent the new natural surface after a cut i would say solid stratum is the best option too.

All of these semantic objects can have geometry formed from a Tin, but the purpose of that Tin is given by the semantic object type.

with that I will merge this anyway! :D

**Pull request merged**
