### PR TITLE
UT-Alignment-12d-8

### PR DESCRIPTION
**Pull request by LeeGregory12d**
## Unit test

alignment with start chainage of 1000, left arc in horizontal and crest and sag parabolas for vertical

My understanding is that nothing will change in the `IfcAlignmentVerticalSegment`
from UT-Alignment-12d-7 because `IfcAlignmentVerticalSegment.StartDistAlong` is only measured from the start of the horizontal
and ignores `IfcAlignmentHorizontal.StartDistAlong`

Axis is fudged because there is no IFC alignment geometry

## Covered topics

*tick one/many*

- [x] project setup
- [ ] georeferencing
- [x] alignment semantics
- [ ] alignment geometry
- [ ] linear placement
- [ ] project breakdown structure / spatial structure
- [ ] terrain
- [ ] triangulated irregular network
- [ ] open cross profile
- [ ] sectioned surface & solid
- [ ] pavement & course
- [ ] surface feature
- [ ] earthworks
- [ ] geotechnics
- [ ] longitudinal products (barriers, guardrail, ...)
- [ ] interchange
- [ ] structural
- [ ] drainage
- [ ] signage
- [ ] road furniture
- [ ] rail furniture
- [ ] ports & waterways furniture
- [ ] bridge furniture

### CODE REVIEW

**Review by pjanck — APPROVED** [review]
LFTM

**Comment by pjanck** [comment]
Following the changes to the schema, (we are now at `RC3`), we ask you to update your IFC files accordingly. The schema can be found [here](https://github.com/bSI-InfraRoom/IFC-Specification/blob/main/IFC4x3_RC3.exp). The checking procedure for IFC files has been updated - please merge in the current state of the `main` branch.

**Review by pjanck — APPROVED** [review]
LFTM seen in @jonm GeometryGym implementation

**Review by jmirtsch — APPROVED** [review]
I have reviewed this pull request, and can successfully view the alignment curve in the Geometry Gym Rhino3d plugin. This import seems consistent with the provided description.

**Pull request merged**
