### PR TITLE
UT-Georeferencing-Earthworks-12d-1

### PR DESCRIPTION
**Pull request by LeeGregory12d**
## Unit test

small georeferenced example with cut and fill

## Covered topics

*tick one/many*

- [x] project setup
- [x] georeferencing
- [ ] alignment semantics
- [ ] alignment geometry
- [ ] linear placement
- [ ] project breakdown structure / spatial structure
- [ ] terrain
- [x] triangulated irregular network
- [ ] open cross profile
- [ ] sectioned surface & solid
- [ ] pavement & course
- [ ] surface feature
- [x] earthworks
- [ ] geotechnics
- [ ] longitudinal products (barriers, guardrail, ...)
- [ ] interchange
- [ ] structural
- [ ] drainage
- [ ] signage
- [ ] road furniture
- [ ] rail furniture
- [ ] ports & waterways furniture
- [ ] bridge furniture

### CODE REVIEW

**Comment by jmirtsch** [comment]
This is a great test file, thanks for creating it.
I have two comments.  First, there is a spatial containment restriction on feature elements found here:
https://standards.buildingsmart.org/IFC/DEV/IFC4_3/RC2/HTML/link/ifcfeatureelement.htm
Explicitly As a subordinate part being fully dependent on the master element the IfcFeatureElement shall have no independent containment relationship to the spatial structure.

The SELF\IfcElement.ContainedInStructure relationship shall be NIL.

So the earthworkscut element should not be in a containment relationship, only as you related it to the stratum.  If this is necessary, the concept should be reviewed.

210301 subtraction element in containment


I'm not sure facilities are the right classification to use in the spatial structure, but others might comment on this.

**Comment by LeeGregory12d** [comment]
Jon,
UT-Earthworks-12d-2 will also have the same problem.

**Comment by pjanck** [comment]
Following the changes to the schema, (we are now at `RC3`), we ask you to update your IFC files accordingly. The schema can be found [here](https://github.com/bSI-InfraRoom/IFC-Specification/blob/main/IFC4x3_RC3.exp). The checking procedure for IFC files has been updated - please merge in the current state of the `main` branch.

**Comment by LeeGregory12d** [comment]
I have updated the IFC file so that IfcEarthworkCut is not included in a Spatial Structure as it is to take it from the element it is a Void of.
However with regards to Jon's comment about it - " If this is necessary, the concept should be reviewed."
I don't know if any of the storylines, or any other application, has a problem with  IfcEarthworkCut always having to be in the same Spatial Structure as the element it is voiding.

**Review by AlexBrad1eyCT — APPROVED** [review]
Looks fine to me

**Pull request merged**
