### PR TITLE
Unit test for Rumble strip from Indiana DoT

### PR DESCRIPTION
**Pull request by larswik**
## Unit test

Testing rumble strip objects (IfcSurfaceFeature/RUMBLESTRIP) in a decomposition of IfcPavement and IfcCourse from the Indiana DoT storyline [INDOT IR_SLRH-C](https://app.box.com/file/731742565663?s=x8prri9nbc1n0x2bjaezeqxvkr9o03sw)

## Covered topics

*tick one/many*

- [x] project setup
- [ ] georeferencing
- [ ] alignment semantics
- [ ] alignment geometry
- [ ] linear placement
- [x] project breakdown structure / spatial structure
- [ ] terrain
- [ ] triangulated irregular network
- [ ] open cross profile
- [ ] sectioned surface & solid
- [x] pavement & course
- [x] surface feature
- [ ] earthworks
- [ ] geotechnics
- [ ] longitudinal products (barriers, guardrail, ...)
- [ ] interchange
- [ ] structural
- [ ] drainage
- [ ] signage
- [ ] road furniture
- [ ] rail furniture
- [ ] ports & waterways furniture
- [ ] bridge furniture

### CODE REVIEW

**Comment by LeeGregory12d** [comment]
Lars,
I read the RC3 file and did get rumple strips IfcSurfaceFeature which you can see in white and blue in Perspective view 4.
The IfcCourse also came in and looked the same at the IFC 4 file.

However the IfcCourse did seem a bit strange but it looks in same in 12d and BimVision, and the same as you image PavementElements.png. However check if purple element of the  Left-Hand-Side does really look like that in the authorising package (GlobalId  1t1539DXXBbBsecxW52L9k).

RumbleStrip-INDOT-12d

**Comment by larswik** [comment]
Besides the geometric artifact (Derek was going to look into that this week), I think that my IFC file is now fine. I also copied over the property sets from the original file. Great if @LeeGregory12d can check (RumbleStrip-INDOT.ifc).
@SergejMuhic mentioned missing concept templates for surface features at the property harmonization meeting. Can you also please check this file (please ignore the geometry artifacts which come from the input data)?

**Comment by LeeGregory12d** [comment]
The geometry in the new RumbleStrip-INDOT.ifc looks correct.
Idiana_DOT_12d_1-before-text

**Review by LeeGregory12d — APPROVED** [review]
The geometry in the new RumbleStrip-INDOT.ifc looks correct to me.
Idiana_DOT_12d_1

**Review by pjanck — APPROVED** [review]
Seen the content in @LeeGregory12d viewer, LFTM.

**Review by jmirtsch — COMMENTED** [review]
I have reviewed this pull request, and can successfully view the project data in the Geometry Gym Rhino3d plugin. This import seems consistent with the provided description.

**Comment by LeeGregory12d** [comment]
I have read the data into 12d Model and the geometry look correct.
Also the IfcPavement and IfcCourse matched the file and the properties for the four IfcCourse appeared correct.

**Pull request merged**
