### PR TITLE
Update Tin-1 to RC3

### PR DESCRIPTION
**Pull request by LeeGregory12d**
Update IFC file to RC3
Remove `_` from file names
Remove `UT_` and `UT-` from file names

## Unit test

This scenario has a simple TIN with some holes/voids. 

## Covered topics

*tick one/many*

- [x] project setup
- [ ] georeferencing
- [ ] alignment semantics
- [ ] alignment geometry
- [ ] linear placement
- [ ] project breakdown structure / spatial structure
- [ ] terrain
- [x] triangulated irregular network
- [ ] open cross profile
- [ ] sectioned surface & solid
- [ ] pavement & course
- [ ] surface feature
- [ ] earthworks
- [ ] geotechnics
- [ ] longitudinal products (barriers, guardrail, ...)
- [ ] interchange
- [ ] structural
- [ ] drainage
- [ ] signage
- [ ] road furniture
- [ ] rail furniture
- [ ] ports & waterways furniture
- [ ] bridge furniture

### CODE REVIEW

**Comment by pjanck** [comment]
I'm unsure: is this the expected result?

grafik

**Review by AlexBrad1eyCT — CHANGES_REQUESTED** [review]
since the RC2 version of Tin-1 an intermediate `IfcFacility` has crept in and become the parent of the IfcSolidStratum, this is not the intended structure it should be on `IfcSite` as before and as there is no 'built' elements there is no need for an IfcFacility.

If i am wrong please enlighten me! :D
Once this is sorted i will Merge!

**Comment by LeeGregory12d** [comment]
Alex,
I could wriggle out of this by saying the tin represents the new surface and hence is a "built" element.

But the truth is that Spatial Structure is a totally alien concept for our Surveying and Civil Design software - well to me anyway. And until I can figure out how Spatial Structure is used from the initial survey, through concept, preliminary and  detailed design, then onto construction, and finally for as built, Spatial Structure is still a "work in progress" in our software.

**Comment by LeeGregory12d** [comment]
Alex,
Can you just pretend that all the tins are "as-built" surfaces and pass them :)

It took me ages to change my 25 Unit tests from RC2 to RC3, to double check all the Alignments and other results, and update the readme.md's to the new conventions,  and I have now run out of enthusiasm to work on them.

Instead I'd like to get onto my Unit Tests for Drainage where a million other questions and horrors will come arise :(

**Comment by AlexBrad1eyCT** [comment]
no problem lee, i understand and thanks alot for all your efforts on this, i will merge all the tin and earthworks with this particular issue, and look forward to the extensive drainage discussions! :D

**Pull request merged**
